#!/usr/bin/env python

import sys

from rqt_generic_hud.generic_hud import GenericHUD
from rqt_gui.main import Main

plugin = 'rqt_generic_hud'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
